const temuan = [
    {
        id: 1,
        judul: "Event pause salah emit", 
        tingkatKeparahan: "High",
        kategori: "Event",
        deskripsi: "Fungsi pauseSystem mengeluarkan event saat sistem dipause.",
        dampak: "Monitoring dan backend dapat salah membaca status sistem.",
        contohKode: "pauseSystem() dipanggil tetapi event Unpaused yang tercatat.",
        rekomendasi: "Emit event Paused() saat pauseSystem dipanggil.",
    },
    {
        id: 2,
        judul: "Tidak ada fungsi unpause", 
        tingkatKeparahan: "Critical",
        kategori: "Logic",
        deskripsi: "Kontrak tidak menyediakan fungsi untuk membuka kembali sistem.",
        dampak: "Sistem dapat terkunci selamanya.",
        contohKode: "paused = true tidak pernah dikembalikan ke false.",
        rekomendasi: "Tambahkan fungsi unpauseSystem dengan modifier onlyAdmin.",
    },
    {
        id: 3,
        judul: "Sentralisasi penuh pada admin", 
        tingkatKeparahan: "High",
        kategori: "Critical",
        deskripsi: "Admin memiliki kontrol penuh atas saldo pulsa user.",
        dampak: "Admin dapat menyalahgunakan wewenang tanpa batas.",
        contohKode: "Admin memotong pulsa user kapan saja.",
        rekomendasi: "Gunakan multisig atau batasi hak admin.",
    },
    {
        id: 4, 
        judul: "Pulsa dapat dicetak tanpa batas", 
        tingkatKeparahan: "High",
        kategori: "business Logic",
        deskripsi: "Tidak ada batas maksimal atau total supply pulsa.",
        dampak: "Inflasi pulsa dan manipulasi data.",
        contohKode: "Admin melakukan topUp dalam jumlah besar.",
        rekomendasi: "Tambahkan totalSupply dan batas maksimum.",
    },
    {
        id: 5, 
        judul: "Tidak ada sumbe ekonomi pulsa", 
        tingkatKeparahan: "Medium",
        kategori: "Design",
        deskripsi: "Pulsa tidak terhubung dengan pembayaran atau aset nyata.",
        dampak: "Pulsa hanya angka tanpa nilai ekonomi.",
        contohKode: "TopUp dilakukan tanpa ETH atau token.",
        rekomendasi: "Hubungkan topUp dengan mekanisme pembayaran.",
    },
    {
        id: 6, 
        judul: "Admin dapat memotong pulsa tanpa persetujuan", 
        tingkatKeparahan: "High",
        kategori: "Access Control",
        deskripsi: "Admin dapat mengurangi saldo user secara sepihak.",
        dampak: "User tidak memiliki kepemilikan nyata.",
        contohKode: "deductPulsa(user, amount).",
        rekomendasi: "Tambahkan persetujuan atau mekanisme dispute.",
    },
    {
        id: 7, 
        judul: "Event penggunaan pulsa ambigu", 
        tingkatKeparahan: "Medium",
        kategori: "Event",
        deskripsi: "Event PulsaUsed digunakan user dan admin.",
        dampak: "Audit trail menjadi tidak jelas.",
        contohKode: "PulsaUsed dipanggil dar useMyPulsa dan eductPulsa.",
        rekomendasi: "Pisahkan event untuk user dan admin.",
    },
    {
        id: 8,
        judul: "Tidak ada identitas layanan",
        tingkatKeparahan: "Medium",
        kategori: "Business Logic",
        deskripsi: "Penggunaan pulsa tidak terikat ke layanan tertentu.",
        dampak: "Tidak dapat diverifikasi penggunaan saldo.",
        contohKode: "useMyPulsa hanya mengurangi saldo.",
        rekomendasi: "Tambahkan parameter layanan atau tujuan penggunaan.",
    },
    {
        id: 9, 
        judul: "Tidak ada pemulihan admin", 
        tingkatKeparahan: "High",
        kategori: "Security",
        deskripsi: "Jika private key admin hilang, sistem tidak dapat dipulihkan.",
        dampak: "Kontrak terkunci permanen.",
        contohKode: "Admin kehilangan akses wallet.",
        rekomendasi: "Gunakan multisig atau recovery address.",
    },
    {
        id: 10, 
        judul: "Admin dapat diganti ke address salah",
        tingkatKeparahan: "Medium",
        kategori: "Logic",
        deskripsi: "Admin bisa diganti ke address yang tidak valid secara opersional.",
        dampak: "Sistem kehilangan kontril.",
        contohKode: "changeAdmin(address burn).",
        rekomendasi: "Validasi address admin lebih ketat.",
    },
    {
        id: 11, 
        judul: "Privasi saldo user terbuka",
        tingkatKeparahan: "Low",
        kategori: "Design",
        deskripsi: "Saldo pulsa user dapat dilihat publik.",
        dampak: "Kebocoran data pengguna.",
        contohKode: "getPulsa(user).",
        rekomendasi: "Batasi akses atau gunakan permission.",
    },
    {
        id: 12, 
        judul: "Modifier pause tidak konsisten",
        tingkatKeparahan: "Low",
        kategori: "Logic",
        deskripsi: "Admin masih dapat mengubah admin saat pause.",
        dampak: "State bisa berubah saat kondisi darurat.",
        contohKode: "changeAdmin saat paused.",
        rekomendasi: "Terapkan whenNotPaused pada fungsi admin.",
    },
    {
        id: 13, 
        judul: "Event pulsa tidak digunakan",
        tingkatKeparahan: "Low",
        kategori: "Event",
        deskripsi: "Event Paused dideklarasikan tetap tidak pernah dipanggil.",
        dampak: "Kualitas kode rendah.",
        contohKode: "event Paused tidak pernah emit.",
        rekomendasi: "Gunakan atau hapus event tersebut.",
    },
    {
        id: 14, 
        judul: "Tidak ada versioning kontrak",
        tingkatKeparahan: "Informational",
        kategori: "Operational",
        deskripsi: "Kontrak tidak memiliki informasi versi.",
        dampak: "Sulit melakukan upgrade atau audit lanjutan.",
        contohKode: "tidak ada constant VERSION.",
        rekomendasi: "Tambahkan versi kontrak.",
    },
    {
        id: 15, 
        judul: "Tidak ada migrasi saldo",
        tingkatKeparahan: "High",
        kategori: "Operational",
        deskripsi: "Tidak ada cara memindahkan saldo ke kontrak baru.",
        dampak: "Upgrade sistem beresiko kehilangan anggka.",
        contohKode: "Deplot ulang kontrak.",
        rekomendasi: "Sediakan mekanisme migrasi.",
    },
    {
        id: 16, 
        judul: "Tidak ada snapshot saldo",
        tingkatKeparahan: "Medium",
        kategori: "Design",
        deskripsi: "Saldo tidak bisa dibackup secara on-chain.",
        dampak: "Sulit audit historis.",
        contohKode: "Tidak ada fungsi snapshot.",
        rekomendasi: "Tambahkan snapshot mechanism.",
    },
    {
        id: 17, 
        judul: "Tidak ada rate limit admin",
        tingkatKeparahan: "Medium",
        kategori: "Security",
        deskripsi: "Admin bisa melakukan banyak aksi dalam satu waktu.",
        dampak: "Event spam dan potensi abuse.",
        contohKode: "TopUp massal.",
        rekomendasi: "Tambahkan rate limit atau timelock.",
    },
    {
        id: 18, 
        judul: "Pulsa bukan aset user",
        tingkatKeparahan: "High",
        kategori: "Design",
        deskripsi: "User tidak memiliki kontrol penuh atas pulsa.",
        dampak: "Bertentangan dengan prinsip web3.",
        contohKode: "Admin bebas deduct.",
        rekomendasi: "Batasi pemotongan sepihak.",
    },
    {
        id: 19, 
        judul: "Tidak ada transfer pulsa",
        tingkatKeparahan: "Low",
        kategori: "Business Logic",
        deskripsi: "Pulsa tidak bisa dipindahkan antar user.",
        dampak: "Kurang fleksibel.",
        contohKode: "Tidak ada fungsi transfer.",
        rekomendasi: "Tambahkan fungsi transfer opsional.",
    },
    {
        id: 20,  
        judul: "Tidak ada approval system",
        tingkatKeparahan: "Medium",
        kategori: "Access Control",
        deskripsi: "User tidak bisa memberi izin penggunaan pulsa.",
        dampak: "Kontrol user terbatas.",
        contohKode: "Admin deduct tanpa izin.",
        rekomendasi: "Tambahkan mekanisme approve.",
    },
    {
        id: 21, 
        judul: "Pulsa hanya counter angka",
        tingkatKeparahan: "Medium",
        kategori: "Design",
        deskripsi: "Pulsa tidak memiliki properti aset.",
        dampak: "Blockchain tidak menambah trust.",
        contohKode: "Mapping sederhana.",
        rekomendasi: "Evaluasi kebutuhan blockchain.",
    },
    {
        id: 22, 
        judul: "Tidak ada audit trail lengkap",
        tingkatKeparahan: "Medium",
        kategori: "Operational",
        deskripsi: "Event tidak menyimpan konteks penuh.",
        dampak: "Sulit audit.",
        contohKode: "PulsaUsed tanpa alasan.",
        rekomendasi: "Tambahkan metadata event.",
    },
    {
        id: 23, 
        judul: "Pulsa bersifat one-way",
        tingkatKeparahan: "Critical",
        kategori: "Logic",
        deskripsi: "Pause tidak bisa dibatalkan.",
        dampak: "Sistem mati permanen.",
        contohKode: "paused = true selamanya.",
        rekomendasi: "Tambahkan unpauseSystem.",
    },
    {
        id: 24,
        judul: "Tidak ada emergency mode",
        tingkatKeparahan: "Medium",
        kategori: "Security",
        deskripsi: "Tidak ada mode darurat selain pause.",
        dampak: "Respons inseden terbatas.",
        contohKode: "Hanya pause tersedia.",
        rekomendasi: "Tambahakan emergency control.",
    },
    {
        id: 25, 
        judul: "Tidak ada audit supply",
        tingkatKeparahan: "Medium",
        kategori: "Business Logic",
        deskripsi: "Total pulsa beredar tidak diketahui.",
        dampak: "Tidak transparan.",
        contohKode: "Tidak ada totalSupply.",
        rekomendasi: "Catat total pulsa",
    },
    {
        id: 26,
        judul: "Tidak ada user consent log",
        tingkatKeparahan: "Low",
        kategori: "Operational",
        deskripsi: "Tidak ada bukti persetujuan user.",
        dampak: "Sengketa sulit dibuktikan.",
        contohKode: "Dedust tanpa log izin.",
        rekomendasi: "Tambahkan event consent.",
    },
    {
        id: 27,
        judul: "Blockchain tidak menambah trust",
        tingkatKeparahan: "Informational",
        kategori: "Design",
        deskripsi: "Semua keputusan terpusat.",
        dampak: "Nilai blockchain minim.",
        contohKode: "Admin mengontrol semua.",
        rekomendasi: "Evaluasi arsitektur.",
    },
    
    {
        id: 28,
        judul: "Kontrak berperilaku seperti database",
        tingkatKeparahan: "Informational",
        kategori: "Design",
        deskripsi: "Tidak ada trustless mechanism.",
        dampak: "Lebih cocok database traditional.",
        contohKode: "Admin full control.",
        rekomendasi: "Pertimbangkan off-chi"
    },
]